### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by dpoetzsch** [IBM/node-celery-ts#44]
I was looking for a more recent (maintained) version of `node-celery` and found your project.

However installation is broken because you did not publish the `dist` folder but only the `src` folder to npm. It works if I manually run `cd node_modules/celery-ts && npm install && npm run build`.

Probably a `prepublish` trigger is missing?

**Comment by Gregory-Meyer** [comment]
@cwill747 

This is now fixed in [Release 1.1.0](https://github.com/IBM/node-celery-ts/pull/32) by 1eb56cf, currently under review. For now, I suggest installing with `npm install ibm/node-celery-ts#rc/1.1.0` and listing it in `package.json` as: `"dependencies": { "celery-ts": "github:ibm/node-celery-ts#rc/1.1.0"  }`.

**Comment by dpoetzsch** [comment]
Cool thanks

**Comment by cwill747** [comment]
1.1.0 has been released!
